### ISSUE TITLE
feature request: support urls in mpv-play

### ISSUE THREAD

**Issue by japhir** [kljohann/mpv.el#11]
I'd expect 
```elisp
(mpv-play "https://youtu.be/AALYPv5xSos")
```
to work, because running `mpv url` from commandline does work. However, this returns `t` without any further info.
The issue is related to what's happening in org-media-note https://github.com/yuchen-lea/org-media-note/issues/10.

When I try to run it on a different video (the one suggested in above issue), I do get a backtrace:

```elisp
  (mpv-play "www.bilibili.com/video/BV16t411n7vJ")
```

```
Debugger entered--Lisp error: (error "Failed to connect to mpv")
  signal(error ("Failed to connect to mpv"))
  error("Failed to connect to mpv")
  mpv-start("/home/japhir/org/www.bilibili.com/video/BV16t411n7...")
  mpv-play("www.bilibili.com/video/BV16t411n7vJ")
  eval((mpv-play "www.bilibili.com/video/BV16t411n7vJ") nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
EDIT: ah, above backtrace is because the url doesn't have `http://` in front of `www`

**Comment by japhir** [comment]
https://github.com/yuchen-lea/org-media-note/issues/10 has now implemented this functionality, so I'm not sure if mpv.el still needs to implement it.

**Comment by kljohann** [comment]
The reason this does not work is that the interactive command `mpv-play` was created with files in mind (in particular it will prompt for existing files in interactive use). There is `mpv-start` (which accepts any string and passes it on to mpv), but only for non-interactive use so far (so `(mpv-start "https://…")` should already work).
A new `mpv-play-url` command with an `interactive` form similar to `eww` might also be nice to have here, so I'll likely add it when I find the time. I'm glad that there already is a workable solution for you, in the meantime. (Also, org-media-note seems quite convenient. :slightly_smiling_face:)

**Comment by shishimaru** [comment]
@japhir @kljohann 
Hi all,

How about using mpv-start ? I could play the YouTube video with mpv.el.

`(mpv-start "https://youtu.be/AALYPv5xSos")`

**Comment by hwiorn** [comment]
I didn't know #14 in here already.
I got a similar issue and I have implemented mpv.el playing URLs.

mpv uses youtube-dl and mpv.el needs to check `youtube-dl` exists in `PATH` when it accesses the URLs.
If not, mpv will get failure always.

```elisp
(defun mpv-play (path)
  "Start an mpv process playing the file at PATH.

You can use this with `org-add-link-type' or `org-file-apps'.
See `mpv-start' if you need to pass further arguments and
`mpv-default-options' for default options."
  (interactive "fFile: ")
  (let ((url-scheme (url-type (url-generic-parse-url path))))
    (if (or (not url-scheme) (string-equal "file" url-scheme))
        ;; Local file
        (mpv-start (expand-file-name path))
      (unless (executable-find "youtube-dl"))
        (message "Warning: mpv needs the youtube-dl program to play internet videos")
      (mpv-start path))))
```
