### ISSUE TITLE
Drop support for Emacs 24?

### ISSUE THREAD

**Issue by progfolio** [kljohann/mpv.el#16]
Package-lint warns:

```
179:20: error: You should depend on (emacs "25.1") if you need `alist-get'.
180:18: error: You should depend on (emacs "25.1") if you need `alist-get'.
```

I think it's safe to bump the min Emacs version to 25.1 unless you have a personal reason for keeping it that low.

**Comment by kljohann** [comment]
Fixed, thanks for reporting this! :+1:
