### ISSUE TITLE
Just return the playback-position, in seconds, and don't insert it

### ISSUE THREAD

**Issue by mihaiolteanu** [kljohann/mpv.el#2]
Instead of inserting the "h :m :s" with `mpv-insert-playback-position`, return the playback position as it's returned by mpv itself: `mpv-playback-position` or something similar.

**Reason**: Use mpv.el for other purposes besides org note taking.

**Comment by kljohann** [comment]
That also sounds quite useful. The main reason for the current approach is that there isn't a blocking interface for the mpv calls yet (see issue #3).
