### ISSUE TITLE
Question:  What is the purpose of org-mpv-complete-link?

### ISSUE THREAD

**Issue by g-gundam** [kljohann/mpv.el#22]
## org-mpv-complete-link?

First, I want to thank you for writing mpv.el.  It's mostly working for me, and I've been able to apply the configuration tips in the wiki successfully to integrate mpv.el with org-mode.  With that said, I have a question about this code from the [mpv.el wiki](https://github.com/kljohann/mpv.el/wiki).

```elisp
(org-link-set-parameters "mpv" :follow #'mpv-play)
(defun org-mpv-complete-link (&optional arg)
  (replace-regexp-in-string
   "file:" "mpv:"
   (org-link-complete-file arg)
   t t))
```

The `org-mpv-complete-link` function is defined, but nothing seems to reference it.  What is its purpose?

## A minor fix to org-metareturn-insert-playback-position

```elisp
(defun org-metareturn-insert-playback-position ()
  "Insert current mpv playback position when in a timer list."
  (when-let ((item-beg (org-in-item-p)))
    (when (and (boundp 'org-timer-start-time)
               (not org-timer-start-time)
               (mpv-live-p)
               (save-excursion
                 (goto-char item-beg)
                 (and (not (org-invisible-p))
                      (org-at-item-timer-p))))
      (mpv-insert-playback-position t))))
```

I added `(boundp 'org-timer-start-time)` to the list of `and` conditions, because I've found that early in a fresh emacs session, that variable might not be bound yet.

**Comment by kljohann** [comment]
> The `org-mpv-complete-link` function is defined, but nothing seems to reference it. What is its purpose?

Good catch! That seems to have been lost in one of the edits to the wiki page. Can you try the following?
```elisp
(org-link-set-parameters "mpv"
  :follow #'mpv-play :complete #'org-mpv-complete-link)
```
This sets up completion for `org-insert-link`. So ‘mpv’ links will behave similar to ‘file’ links and you are prompted for a file name after you type `C-c C-l mpv: RET`.

> I added `(boundp 'org-timer-start-time)` to the list of `and` conditions, because I've found that early in a fresh emacs session, that variable might not be bound yet.

Sounds good! Feel free to add both improvements to the wiki, if they work for you. Thanks! :+1:

**Comment by kljohann** [comment]
I updated the wiki page, thanks again.
