### ISSUE TITLE
Title: Accept URL in mpv-play

### ISSUE THREAD

**Issue by tvraman** [kljohann/mpv.el#27]
Description:
At present one cannot pass a url eg  youtube-url to function mpv-play 
it calls expand-file-name on its argument which causes urls to
break. Could you perhaps update that function, or add a mpv-play-url?

**Comment by kljohann** [comment]
Thanks for your input. I just merged a variant of #14, which adds an `mpv-play-url` interactive command. Can you take a look whether it does what you need?
 (For non-interactive use there was already `mpv-start`, which just passed arguments on to mpv.)

**Comment by tvraman** [comment]
thanks -- it fits my needs.
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
