### ISSUE TITLE
Request to rename the project

### ISSUE THREAD

**Issue by SylvianHemus** [kljohann/mpv.el#32]
I feel like this project is more oriented around note taking than mpv av management, like https://github.com/isamert/empv.el is. I'd request renaming the project to something like "mpv-annote" or similar. No disrespect

**Comment by kljohann** [comment]
Thanks for your thoughts. It's not primarily geared toward note taking, even though that was one of the initial use cases (thus the arguably outdated tag line in the README). The package's aim was to provide a simple interface to control a single mpv process via its IPC interface. I'm glad that there are now several mpv-related packages for Emacs, so everybody can pick one that works best for them.
Renaming the package at this stage would probably be confusing and inconvenient for its existing users, so it's not something I would want to do needlessly. Perhaps as a first step linking to alternatives in the README would be helpful? Alternatives are also discoverable via MELPA.
