### ISSUE TITLE
Mpv Library

### ISSUE THREAD

**Issue by xFA25E** [kljohann/mpv.el#5]
Hi, I would like to use your package as a library for my own project (it would be a simple music player). `mpv.el` is great, but it is not very usable as a library. It allows only one instance of mpv at a time.

Are you willing to accept a PR to make this package more library-like? I think that it is possible to add functions that would create sockets and manipulate them. These functions will be used by already existing functions to leave default behaviour.

What do you think? Do you have any suggestions? 
Thanks :)

**Comment by stardiviner** [comment]
This is really a good idea, can you send PR?
